### ISSUE TITLE
docker-lignt模式下本地使用application-local.properties将place_order_tpye设置为queued无法启动应用

### ISSUE THREAD

**Issue by h1deOnBush** [ThoughtsBeta/flash-sale#18]
报错信息：
A component required a bean of type 'com.actionworks.flashsale.app.service.stock.ItemStockCacheService' that could not be found

**Comment by Jevinliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件已收到！谢谢！

**Comment by h1deOnBush** [comment]
已解决
