### ISSUE TITLE
IDEA中jmx文件打开报错

### ISSUE THREAD

**Issue by tanzhou2002** [ThoughtsBeta/flash-sale#19]
IDEA2023.1

打开 flash-sale-pressure-test-full.jmx 文件报错如下（似乎版本不正确）
Cause:
CannotResolveClassException: kg.apc.jmeter.threads.SteppingThreadGroup

 Detail:com.thoughtworks.xstream.converters.ConversionException: 
---- Debugging information ----
cause-exception     : com.thoughtworks.xstream.converters.ConversionException
cause-message       : 
first-jmeter-class  : org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66)
class               : org.apache.jmeter.save.ScriptWrapper
required-type       : org.apache.jmeter.save.ScriptWrapper
converter-type      : org.apache.jmeter.save.ScriptWrapperConverter
path                : /jmeterTestPlan/hashTree/hashTree/kg.apc.jmeter.threads.SteppingThreadGroup
line number         : 799
version             : not available
-------------------------------

**Comment by Jevinliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件已收到！谢谢！

**Comment by Jevinliu** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮件已收到！谢谢！
